### ISSUE TITLE
How to update screen translation?

### ISSUE THREAD

**Issue by AndylgTom** [Mellow-3D/FLY-Screen-RepRap#16]
How can I update the corrected *.tr translation for a screen, is there an instruction? 
Just copy the *.tr file to the card or what?

**Comment by jaysuk** [comment]
currently, it needs to be sent to flymaker so it can be included in a build. 
can you post it here?

**Comment by AndylgTom** [comment]
I see, I thought the same as on the btt screens. I'll upload it later then.

**Comment by AndylgTom** [comment]
Question...
On github I see "Old version interface demo source code". Where is the **current** version of the source code? Will it be available? 
Because if I start correcting the translation, then half of the words do not fit into the given interface, i.e. the length of the translated text in other languages is not consider, although the screen size and space on it allow this.

And is it worth waiting for another update?

**Comment by jaysuk** [comment]
The source is currently closed source. It will be going open source soon but I can't tell you when
