### ISSUE TITLE
Firmware compilation

### ISSUE THREAD

**Issue by AndylgTom** [Mellow-3D/FLY-Screen-RepRap#17]
Thanks for the sources.
How to compile own firmware version correctly?
If I do it through a FlyThings IDE, I get a file at the output **libqtgui.so**, but I need the file with the extension ***.img**. On the screen I can see the changes in the interface by clicking _Start the Fly Things application_, but how do I compile **update.img** to flash from sd card?

**Comment by jaysuk** [comment]
See here https://teamgloomy.github.io/fly_firmware_compile.html
